version: "3.2"
services:
  back-app:
    build:
      context: ./book_application_back/
    image: book_application_back
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - DB_PATH=jdbc:postgresql://postgres:5454/book_service
      - MINIO_ACCESS_KEY=BOOK_ACCESS_KEY
      - MINIO_SECRET_KEY=BOOK_SECRET_KEY
    depends_on:
      - postgres
      - minio
  front-app:
    build:
      context: ./book_application_front/
    image: book_application_front
    ports:
      - 3000:80
    depends_on:
      - back-app
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5454:5432
    volumes:
    - type: volume
      source: ./data/postgres  # your path for db volumes
      target: /var/lib/postgresql/data
  minio:
    image: minio/minio
    ports:
    - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=BOOK_ACCESS_KEY
      - MINIO_SECRET_KEY=BOOK_SECRET_KEY
    volumes:
    - type: volume
      source: /mnt/data # your path for minio volumes
      target: /data
